pipeline:
  build:
    image: elixir
    environment:
      - MIX_ENV=test
    commands:
      - mix local.hex --force
      - mix deps.get

  test:
    image: elixir
    environment:
      - MIX_ENV=test